apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "dast-operator.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "dast-operator.fullname" . }}-certificate
spec:
  dnsNames:
  - "{{ include "dast-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc"
  - "{{ include "dast-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: {{ include "dast-operator.fullname" . }}-selfsigned-issuer
  secretName: {{ include "dast-operator.tlsSecretName" . }}
