name: Lint and Test Charts
on:
  pull_request:
    branches:
      - master
    paths:
      - 'charts/**'
      - '.github/workflows/chart-lint.yml'



jobs:

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v5

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Run chart-testing (lint)
        id: lint
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: "1.27"

      - name: Validate removed Kubernetes APIs
        run: make validate-manifests
